# Nombre del flujo de trabajo de Integración Continua
name: CI - Node Express

# Define los eventos que disparan el flujo
on:
  push:
    branches: [ "main" ] # Se ejecuta cuando hay cambios en la rama principal
  pull_request:
    branches: [ "main" ] # Se ejecuta cuando se crea un PR hacia la rama principal

# Lista de trabajos a realizar
jobs:
  test:
    # Sistema operativo sobre el que correrán las pruebas
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descarga el código del repositorio en el contenedor
      - name: Obtener codigo
        uses: actions/checkout@v4

      # Paso 2: Instala y configura el entorno de Node.js
      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0 # Define la versión específica de Node a utilizar
      
      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test